pipeline {
    agent any

    environment {
        DOTNET_CLI_HOME = '/tmp/.dotnet'

        REGISTRY = "localhost:5000"
        IMAGE_NAME = "learningenglish-api"
        IMAGE_TAG = "dev"
        FULL_IMAGE = "${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Restore') {
            steps {
                sh 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build -c Release --no-restore'
            }
        }

        stage('Test') {
            steps {
                sh 'dotnet test -c Release --no-build --logger trx --results-directory TestResults'
            }
        }

        stage('Publish') {
            steps {
                sh '''
                dotnet publish LearningEnglish.API/LearningEnglish.API.csproj \
                  -c Release \
                  -o publish
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                docker build -t ${FULL_IMAGE} .
                '''
            }
        }

        stage('Docker Push') {
            steps {
                sh '''
                docker push ${FULL_IMAGE}
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker compose down || true
                docker compose up -d
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'TestResults/**/*.trx', allowEmptyArchive: true
        }
        success {
            echo 'CI/CD pipeline SUCCESS'
        }
        failure {
            echo ' CI/CD pipeline FAILED'
        }
    }
}
